umls_path: /export/home/cse200093/scratch/BioMedics/data/umls/full_atc_str_2023AB.json
labels_column_name: ATC
synonyms_column_name: STR
# res_path: /export/home/cse200093/Jacques_Bio/BioMedics/data/maladie_de_takayasu_norm/res.json

label_to_normalize: Chemical_and_drugs
qualifiers:
  - Temporality
  - Certainty
  - Action
  - Negation
column_name_to_normalize: term_to_norm
coder_device: cuda:0
coder_save_umls_embeddings_dir: false
coder_save_umls_des_dir: false
coder_save_umls_labels_dir: false
coder_save_data_embeddings_dir: false
coder_normalize: true
coder_summary_method: CLS
coder_tqdm_bar: true
coder_cased: false
coder_batch_size: 128
coder_stopwords:
  - for
  - assay
  - by
  - tests
  - minute
  - exam
  - with
  - human
  - moyenne
  - in
  - to
  - from
  - analyse
  - test
  - level
  - fluid
  - laboratory
  - determination
  - examination
  - releasing
  - quantitative
  - screening
  - and
  - exploration
  - factor
  - method
  - analysis
  - laboratoire
  - specimen
  - or
  - typing
  - of
  - concentration
  - measurement
  - detection
  - procedure
  - identification
  - numeration
  - hour
  - retired
  - technique
  - count
coder_remove_stopwords_terms: true
coder_remove_special_characters_terms: true
coder_remove_stopwords_umls: true
coder_remove_special_characters_umls: true