script:
  label_key: BIO_comp
  labels_to_remove: 
    - BIO
  brat_dirs: 
    - /export/home/cse200055/brat_data/Etienne/ai_triomph/EDS-biomedic/RCP
  output_dirs: 
    - /export/home/cse200055/Etienne/ai_triomph/data/extracted/RCP
