script:
  label_key: BIO_comp
  labels_to_remove: 
    - BIO
  data_paths: 
    - /export/home/cse200055/Etienne/ai_triomph/data/extracted/CONS_ents.parquet
  output_paths: 
    - /export/home/cse200055/Etienne/ai_triomph/data/extracted/CONS
